#algolia_search:
#  nbResults: 8                  # Retrieve less results on search (default: 20)
#  prefix: %env(SEARCH_PREFIX)%  # Use a prefix for index names based en env var
#  doctrineSubscribedEvents: []  # disable doctrine events (turn off realtime sync)
#  indices:
#    - name: posts
#      class: App\Entity\Post
#      enable_serializer_groups: true
#
#    - name: comments
#      class: App\Entity\Comment
