twig:
    form_themes:
        - 'bootstrap_4_layout.html.twig'
        - '@FOSCKEditor/Form/ckeditor_widget.html.twig'
    default_path: '%kernel.project_dir%/templates'
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    exception_controller: null
    globals:
        renderController: '@App\Controller\RenderController'
        stateRepository: '@App\Repository\StateRepository'
        toolTypeRepository: '@App\Repository\ToolTypeRepository'