vich_uploader:
  db_driver: orm

  mappings:
    tutorial_image:
      uri_prefix: /images/tutorials
      upload_destination: '%kernel.project_dir%/public/images/tutorials'
      namer:
        service: Vich\UploaderBundle\Naming\UniqidNamer
    tutorial_video:
      uri_prefix: /videos/tutorials
      upload_destination: '%kernel.project_dir%/public/videos/tutorials'
      namer:
        service: Vich\UploaderBundle\Naming\UniqidNamer
    item_image:
      uri_prefix: /images/items
      upload_destination: '%kernel.project_dir%/public/images/items'
      namer:
        service: Vich\UploaderBundle\Naming\UniqidNamer
    render_image:
      uri_prefix: /images/render
      upload_destination: '%kernel.project_dir%/public/images/render'
      namer:
        service: Vich\UploaderBundle\Naming\UniqidNamer
    event_image:
      uri_prefix: /images/events
      upload_destination: '%kernel.project_dir%/public/images/events'
      namer:
        service: Vich\UploaderBundle\Naming\UniqidNamer