version: '3'
services:

  apache:
    build: .docker/apache
    container_name: pabba_apache
    ports:
      - 33:80
    volumes:
      - .docker/config/vhosts:/etc/apache2/sites-enabled
      - .:/home/wwwroot/sf4
    depends_on:
      - php

  mysql:
    image: mysql:8.0.16

    command:
      - "--default-authentication-plugin=mysql_native_password"
      - "--max_allowed_packet=32505856"
    container_name: pabba_mysql
    ports:
      - 3350:3306
    volumes:
      - .docker/data/db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: pabba
      MYSQL_USER: root
      MYSQL_PASSWORD: root

  php:
    build: .docker/php
    container_name: pabba_php
    volumes:
      - .:/home/wwwroot/sf4
      - /app-vendor
      - /app-cache
      - /app-logs

  phpmyadmin:
    container_name: pabba_phpmyadmin
    image: phpmyadmin/phpmyadmin
    links:
      - mysql:mysql
    ports:
      - 5003:80
    environment:
      PMA_HOSTS: pabba_mysql
      MYSQL_USERNAME: root
      MYSQL_ROOT_PASSWORD: root


